### ISSUE TITLE
Is that possible to add new button to get the finally binary data that user can upload. 

### ISSUE THREAD

**Issue by Vijaygupta-G** [lidojs/application-example#11]
Here is the big issue, i'm facing to get the binary data on save for development. I want to preview accordingly and upload the data for next uses, that is possible when i have that binary data on my server and get it to display all my collection after edit also possible, if I get and set to this package template

**Comment by Vijaygupta-G** [comment]
I want to add my own template by using this tool and upload to my DB and as user want to edit that is also possible in same way.

**Comment by duyank** [comment]
@vijaypaytune it's possible. you can store template json data to data like `TemplateContent.tsx` file does
