### ISSUE TITLE
Failed to resolve entry for package "@lidojs/design-editor". 

### ISSUE THREAD

**Issue by shykh515** [lidojs/application-example#15]
Failed to resolve entry for package "@lidojs/design-editor". The package may have incorrect main/module/exports specified in its package.json
src/pages/EditorContent.tsx:1:28:
      1 │ import { DesignFrame } from '@lidojs/design-editor';
      didnot find the package

**Comment by duyank** [comment]
Sorry, we removed local development for free users so you cannot install it without a pro license
