### ISSUE TITLE
Mobile Responsive Issues with Layers and Align Mode in Lido JS Demo

### ISSUE THREAD

**Issue by saeb75** [lidojs/application-example#4]
The Lido JS demo is experiencing issues related to the usage of layers and align mode when accessed on mobile devices. The demo, which works well on desktop screens, fails to render properly on mobile screens.

**Comment by duyank** [comment]
thanks for your comment.
Currently, LidoJS is only supported on Desktop. The mobile version just has enough functions to show it can be worked on mobile devices. The current issue is UI only. I'm still developing some features before updating them
