### ISSUE TITLE
resize function is not working for images 

### ISSUE THREAD

**Issue by roshankc123** [lidojs/application-example#7]
hey, resize function is only resizing main page but not the selected layer.

**Comment by princetechs** [comment]
its working fine, can you please describe with full details so that i can help you with?

**Comment by roshankc123** [comment]
i uploaded an image, selected the image, then tried to resize it from the resize navbar item, on doing so, it only resize the whole page but not the image i selected. 
something like this, 
<img width="936" alt="image" src="https://github.com/lidojs/canva-clone/assets/47151288/b820a5be-9dce-4112-8f82-495bf966d636">
