### ISSUE TITLE
window is not defined in NextJS 

### ISSUE THREAD

**Issue by emirhangunec** [lidojs/application-example#8]
First of all, I congratulate everyone who contributed. This is an amazing project. I managed to integrate to nextjs14. And figured out working with emotion in nextjs. Everything works fine, except i can not edit any of the text on the editor. I can edit on the data, and works fine but when I double click the text, it does nothing.
 I assume that a  `prosemirror` SSR issue because it says `window is undefined`. I tried:
add `"use client"` for every component,
use dynamic loading feature while loading `<Test/>`  from `next/dynamic` for disabling SSR.

I guess you could update where you import and use prosemirror, and force the wait for `window` like:

 ```
const [isLoading, setIsLoading] = useState(true);
    useEffect(() => {
        console.log(window);
        if (typeof window !== "undefined") {
            setIsLoading(false);
        }
    }, []);
```
again, congrats on hard work. This is impressive work.

**Comment by duyank** [comment]
Could you create a demo link for it?

**Comment by emirhangunec** [comment]
https://github.com/emirhangunec/alpseroglu_saas this is the repo, https://alpseroglu-saas.vercel.app/dashboard/editor and this is the demo. I know sidebar assets doesn't loading issue, I have'nt implemented api path or asset file. (This has no impact on my issue, I implemented but issue is continuied)

**Comment by emirhangunec** [comment]
no longer need, thanks all.
